In [1]:
pip install pandas scikit-learn matplotlib jupyter

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.9-cp314-cp314-win_amd64.whl.metadata (52 kB)
Collecting jupyter
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.6-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from matplotlib) (26.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting notebook (from jupyter)
  Downloading notebook-7.5.6-py3-none-any.whl.metadata (10 kB)
Collecting jupyter-console (from jupyter)
  Downloading jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting nbconvert (from jupyter)
  Downloading nbconvert-7.17.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: ipykernel in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from jupyter) (7.2.0)
Collecting ipywidgets (from jupyter)
  Downloading ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyterlab (from jupyter)
  Downloading jupyterlab-4.5.7-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.5 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipykernel->jupyter) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipykernel->jupyter) (9.13.0)
Requirement already satisfied: jupyter-client>=8.8.0 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipykernel->jupyter) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipykernel->jupyter) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipykernel->jupyter) (0.2.2)
Requirement already satisfied: nest-asyncio>=1.4 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil>=5.7 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipykernel->jupyter) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipykernel->jupyter) (6.5.5)
Requirement already satisfied: traitlets>=5.4.0 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipykernel->jupyter) (5.15.0)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: wcwidth in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel->jupyter) (0.8.7)
Requirement already satisfied: platformdirs>=2.5 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->jupyter) (4.9.6)
Requirement already satisfied: executing>=1.2.0 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (3.0.1)
Requirement already satisfied: pure-eval in c:\Users\Borko\Python for AIatWORK\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets->jupyter)
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets->jupyter)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter)
  Downloading async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Collecting httpx<1,>=0.25.0 (from jupyterlab->jupyter)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jinja2>=3.0.3 (from jupyterlab->jupyter)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab->jupyter)
  Downloading jupyter_lsp-2.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server<3,>=2.4.0 (from jupyterlab->jupyter)
  Downloading jupyter_server-2.18.2-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from jupyterlab->jupyter)
  Downloading jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting notebook-shim>=0.2 (from jupyterlab->jupyter)
  Downloading notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Collecting setuptools>=41.1.0 (from jupyterlab->jupyter)
  Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting anyio (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Downloading anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting certifi (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Downloading certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Downloading idna-3.15-py3-none-any.whl.metadata (7.7 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading jupyter_events-0.12.1-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting nbformat>=5.3.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading prometheus_client-0.25.0-py3-none-any.whl.metadata (2.1 kB)
Collecting pywinpty>=2.0.1 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading pywinpty-3.0.3-cp314-cp314-win_amd64.whl.metadata (5.9 kB)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading json5-0.14.0-py3-none-any.whl.metadata (36 kB)
Collecting jsonschema>=4.18.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting requests>=2.31 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading argon2_cffi_bindings-25.1.0-cp39-abi3-win_amd64.whl.metadata (7.5 kB)
Collecting MarkupSafe>=2.0 (from jinja2>=3.0.3->jupyterlab->jupyter)
  Downloading markupsafe-3.0.3-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Collecting attrs>=22.2.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading rpds_py-0.30.0-cp314-cp314-win_amd64.whl.metadata (4.2 kB)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading python_json_logger-4.1.0-py3-none-any.whl.metadata (3.7 kB)
Collecting pyyaml>=5.3 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting jsonpointer>1.13 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Collecting beautifulsoup4 (from nbconvert->jupyter)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading bleach-6.3.0-py3-none-any.whl.metadata (31 kB)
Collecting defusedxml (from nbconvert->jupyter)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jupyterlab-pygments (from nbconvert->jupyter)
  Downloading jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert->jupyter)
  Downloading mistune-3.2.1-py3-none-any.whl.metadata (1.9 kB)
Collecting nbclient>=0.5.0 (from nbconvert->jupyter)
  Downloading nbclient-0.10.4-py3-none-any.whl.metadata (8.3 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter)
  Downloading pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2<1.5,>=1.1.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading tinycss2-1.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting lark>=1.2.2 (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting cffi>=2.0.0b1 (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading cffi-2.0.0-cp314-cp314-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0b1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert->jupyter)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4->nbconvert->jupyter)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 3.8 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/9.9 MB 3.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 3.7 MB/s eta 0:00:03
   ----------- ---------------------------- 2.9/9.9 MB 3.7 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/9.9 MB 3.7 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.9 MB 3.7 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.9 MB 3.7 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/9.9 MB 3.7 MB/s eta 0:00:01
   ----------------------------- ---------- 7.3/9.9 MB 3.7 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 3.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 3.5 MB/s  0:00:02
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 3.6 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.1 MB 3.7 MB/s eta 0:00:02
   ---------- ----------------------------- 2.1/8.1 MB 3.7 MB/s eta 0:00:02
   -------------- ------------------------- 2.9/8.1 MB 3.7 MB/s eta 0:00:02
   ------------------ --------------------- 3.7/8.1 MB 3.7 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.1 MB 3.7 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.1 MB 3.7 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.1 MB 3.6 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.1 MB 3.6 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 3.6 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 3.4 MB/s  0:00:02
Downloading matplotlib-3.10.9-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.3 MB 3.6 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.3 MB 3.7 MB/s eta 0:00:02
   ---------- ----------------------------- 2.1/8.3 MB 3.7 MB/s eta 0:00:02
   ------------- -------------------------- 2.9/8.3 MB 3.7 MB/s eta 0:00:02
   ----------------- ---------------------- 3.7/8.3 MB 3.7 MB/s eta 0:00:02
   --------------------- ------------------ 4.5/8.3 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 5.0/8.3 MB 3.6 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.3 MB 3.4 MB/s eta 0:00:01
   -------------------------- ------------- 5.5/8.3 MB 3.2 MB/s eta 0:00:01
   --------------------------- ------------ 5.8/8.3 MB 2.8 MB/s eta 0:00:01
   --------------------------- ------------ 5.8/8.3 MB 2.8 MB/s eta 0:00:01
   --------------------------- ------------ 5.8/8.3 MB 2.8 MB/s eta 0:00:01
   ------------------------------- -------- 6.6/8.3 MB 2.4 MB/s eta 0:00:01
   --------------------------------- ------ 7.1/8.3 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 7.9/8.3 MB 2.6 MB/s eta 0:00:01
   -------------------------------------- - 8.1/8.3 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 2.5 MB/s  0:00:03
Downloading jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)

In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report

In [3]:
df = pd.read_csv("iris.csv")

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [5]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [6]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [7]:
X = df.drop("species", axis=1)

y = df["species"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
numeric_features = X.columns

In [10]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [11]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features)
    ]
)

In [12]:
RandomForestClassifier

sklearn.ensemble._forest.RandomForestClassifier

In [13]:
model_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=42))
])

In [14]:
model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='str'))])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [15]:
y_pred = model_pipeline.predict(X_test)

In [16]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [17]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30